language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - ~/.platformio
addons:
  apt:
    packages:
    - tree
env:
  global:
    # - COMMON_VARS="-lc -lstdc++ -I$HOME/.platformio/packages/framework-arduinoespressif/tools/sdk/libc/xtensa-lx106-elf/include -L$HOME/.platformio/packages/framework-arduinoespressif/tools/sdk/libc/xtensa-lx106-elf/lib"
  matrix:
  # - PLATFORMIO_CI_SRC="$TRAVIS_BUILD_DIR/examples/Melvanimate-example/Melvanimate-example.ino" PLATFORMIO_BUILD_FLAGS="-lstdc++"
  # - PLATFORMIO_CI_SRC="$TRAVIS_BUILD_DIR/examples/Melvanimate-example/Melvanimate-example.ino" PLATFORMIO_BUILD_FLAGS="-lstdc++ -D Debug_ESPManager -D DEBUG_ESP_PORT=Serial "

  - PLATFORMIO_CI_SRC="$TRAVIS_BUILD_DIR/examples/Melvanimate-example/Melvanimate-example.ino"
      PLATFORMIO_BUILD_FLAGS="-DDebugMelvanimate=Serial -DDebugEffectManager=Serial -DDebugEffectHandler=Serial -DDebugEQ=Serial -DDebugMelvanimateMQTT=Serial -DDebugObjectman=Serial -DDebugPalette=Serial -DDebugPropertyManager=Serial"
  - PLATFORMIO_CI_SRC="$TRAVIS_BUILD_DIR/examples/Melvanimate-example/Melvanimate-example.ino"

  - PLATFORMIO_CI_SRC="$TRAVIS_BUILD_DIR/examples/Melvanimate-withESPManager/Melvanimate-withESPManager.ino"
      PLATFORMIO_BUILD_FLAGS="-DDebugMelvanimate=Serial -DDebugEffectManager=Serial -DDebugEffectHandler=Serial -DDebugEQ=Serial -DDebugMelvanimateMQTT=Serial -DDebugObjectman=Serial -DDebugPalette=Serial -DDebugPropertyManager=Serial"
  - PLATFORMIO_CI_SRC="$TRAVIS_BUILD_DIR/examples/Melvanimate-withESPManager/Melvanimate-withESPManager.ino"


install:
  - pip install -U platformio
#   - platformio platforms install espressif --with-package framework-arduinoespressif --with-package ldscripts
#   - rm -rf ~/.platformio/packages/framework-arduinoespressif
# #  - git clone https://github.com/esp8266/Arduino ~/.platformio/packages/framework-arduinoespressif
#   - git clone --branch 2.3.0 --depth 1 https://github.com/esp8266/Arduino ~/.platformio/packages/framework-arduinoespressif
#   - export PATH="$HOME/.platformio/packages/toolchain-xtensa/bin:$PATH"
#   - cd $HOME/.platformio/packages/toolchain-xtensa/lib
#   # update sdk
#   - xtensa-lx106-elf-ar -d libmain.a mem_manager.o
#   - xtensa-lx106-elf-ar d libstdc++.a pure.o
#   - xtensa-lx106-elf-ar d libstdc++.a vterminate.o
#   - xtensa-lx106-elf-ar d libstdc++.a guard.o
#   - xtensa-lx106-elf-ar d libstdc++.a functexcept.o
#   - xtensa-lx106-elf-ar d libstdc++.a del_op.o
#   - xtensa-lx106-elf-ar d libstdc++.a del_opv.o
#   - xtensa-lx106-elf-ar d libstdc++.a new_op.o
#   - xtensa-lx106-elf-ar d libstdc++.a new_opv.o

  # update ld script
 #  - cd $HOME/.platformio/packages/ldscripts
 #  - rm -f esp8266.flash.common.ld
 #  - wget https://gist.githubusercontent.com/sticilface/441a64cb7d73799afab6fcaa4ad6bdee/raw/34d27106ae274fc866bdb332c89f43ed63e5c0c2/esp8266.flash.common.ld
 # # finsih sdk updates
  - cd $TRAVIS_BUILD_DIR
  - echo "10606" > ~/.platformio/packages/framework-arduinoespressif/version.txt
  - mkdir /tmp/build
  - mkdir $TRAVIS_BUILD_DIR/libs
  #- git clone https://github.com/bblanchon/ArduinoJson          $TRAVIS_BUILD_DIR/libs/ArduinoJson
  # - git clone https://github.com/me-no-dev/ESPAsyncTCP                         $TRAVIS_BUILD_DIR/libs/ESPAsyncTCP
  # - git clone https://github.com/me-no-dev/ESPAsyncWebServer                   $TRAVIS_BUILD_DIR/libs/ESPAsyncWebServer
  # - git clone https://github.com/Makuna/NeoPixelBus                            $TRAVIS_BUILD_DIR/libs/NeoPixelBus
  #- git clone https://github.com/knolleary/pubsubclient                        $TRAVIS_BUILD_DIR/libs/pubsubclient
  # - git clone https://github.com/adafruit/Adafruit-GFX-Library                 $TRAVIS_BUILD_DIR/libs/Adafruit-GFX-Library
  - git clone https://github.com/sticilface/ESPmanager          $TRAVIS_BUILD_DIR/libs/ESPmanager
  # - git clone https://github.com/bblanchon/ArduinoJson                         $TRAVIS_BUILD_DIR/libs/ArduinoJson
  # #- platformio lib install 64    # ArduinoJson
  # - platformio lib install 13    # Adafruit_GFX
  # - platformio lib install 547  # neopixelbus
  # - platformio lib install 89  # pubsubclient
  # # - platformio lib install
  # # - platformio lib install 305  # ESPAsyncTCP
  # # - platformio lib install 306 # ESPAsyncWebServer
  # - platformio lib install 346 # https://github.com/marvinroger/async-mqtt-client
  - platformio lib -g install "ESPAsyncTCP" "ESPAsyncWebServer" "ArduinoJson" "NeoPixelBus" "Adafruit GFX Library" "AsyncMqttClient"

script:
  - platformio ci --board="esp12e" --build-dir="/tmp/build"
    --lib="$TRAVIS_BUILD_DIR"
    --lib="$TRAVIS_BUILD_DIR/libs/ESPmanager"
